#!/usr/bin/python3

# This Python code is a drawing of  Ubuntu Logo in participation/contribution of Ubuntu Community world wide 
# Copyright (C) 2024 Open Source Matters, Inc. All rights reserved.
# Purely written By: Michael M. Quisido III using Python Programming Language
# GNU General Public License version 2 or later.
# For more information email me: mike.quisido@kmcq-gmbh.com

import turtle
	
def animate():
    mikeq = turtle.Turtle()
    mikeq.pen(fillcolor="#ffffff", pencolor="#ffffff", pensize=2)
    mikeq.forward(100)
    
	
window = turtle.Screen()
window.bgcolor("#000080")
	
animate()

window.exitonclick()
