#!/usr/bin/python3

# This Python code is a drawing of  Ubuntu Logo in participation/contribution of Ubuntu Community world wide 
# Copyright (C) 2024 Open Source Matters, Inc. All rights reserved.
# Purely written By: Michael M. Quisido III using Python Programming Language
# GNU General Public License version 2 or later.
# For more information email me: mike.quisido@kmcq-gmbh.com or mike082112@gmail.com

# import for turtle
import turtle
 
# Starting a Working Screen
window = turtle.Screen()
window.title("Intricate Shapes Loop Drawing - Michael M. Quisido III DEMO")
window.bgcolor("#000080")
 
# initializing a turtle instance

mikeqstar = turtle.Turtle()
# Heading Home
mikeqstar.home
# setting up the pen color and size
mikeqstar.pen(pencolor="#ff1ac6", pensize=1)
# Head posistion.
mikeqstar.setpos((-200,0))
# Hiding the head drawing the arrow or turtle
mikeqstar.hideturtle()
# executing loop speed drawing for fast execution.
mikeqstar.speed(7)

# executing loop 100 times 
for kmcq in range(100):
 
       
        # moving head for 400 units forward
        mikeqstar.forward(400)
 
        # rotating the hear for 844 degree right
        mikeqstar.left(844)
        
print(mikeqstar.pos())
              
window.exitonclick()
